In [43]:
team = [
    ('Marta', 20, 'center'),
    ('Ana', 22, 'point guard'),
    ('Gabi', 22, 'shotting guard'),
    ('Luz', 21, 'power forward'),
    ('Lorena', 19, 'small forward')
]

In [44]:
def player_position(players):
    result = []
    for name, age, position in players:
        result.append('Name: {:>19} \nPosition: {:>15}\n'.format(name, position))

    return result

In [45]:
for player in player_position(team):
    print(player)

Name:               Marta 
Position:          center

Name:                 Ana 
Position:     point guard

Name:                Gabi 
Position:  shotting guard

Name:                 Luz 
Position:   power forward

Name:              Lorena 
Position:   small forward



In [46]:
for left in range(7):
    for right in range(left, 7):
        print(f"[{left}|{right}]", end=" ")
    print('\n')

[0|0] [0|1] [0|2] [0|3] [0|4] [0|5] [0|6] 

[1|1] [1|2] [1|3] [1|4] [1|5] [1|6] 

[2|2] [2|3] [2|4] [2|5] [2|6] 

[3|3] [3|4] [3|5] [3|6] 

[4|4] [4|5] [4|6] 

[5|5] [5|6] 

[6|6] 



In [47]:
dominoes = []
for left in range(7):
    for right in range(left, 7):
        dominoes.append((left, right))
dominoes

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 4),
 (4, 5),
 (4, 6),
 (5, 5),
 (5, 6),
 (6, 6)]

In [48]:
import numpy

In [49]:
numpy.array([2, 4, 6])

array([2, 4, 6])

In [50]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot

ModuleNotFoundError: No module named 'pandas'

In [29]:
np.array([2, 4, 6])

array([2, 4, 6])

In [30]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [31]:
from sklearn.metrics import precision_score, recall_score

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
from numpy import array

In [ ]:
array([2,4,6])

In [ ]:
from library.module import *

In [32]:
import datetime  
date = datetime.date(1977, 5, 8)       # assign a date to a variable
print(date)                            # print date
print(date.year)                       # print the year that the date is in

delta = datetime.timedelta(days=30)    # assign a timedelta of 30 days to a 
                                       # variable
print(date - delta)                    # print date of 30 days prior 

1977-05-08
1977
1977-04-08


In [33]:
import math  
print(math.exp(0))          # e**0
print(math.log(1))          # ln(1)
print(math.factorial(4))    # 4! 
print(math.sqrt(100))     

1.0
0.0
24
10.0


In [34]:
import random
print(random.random())          # 0.0 <= X < 1.0
print(random.choice([1, 2, 3])) # choose a random element from a sequence
print(random.randint(1, 10))    # a <= X <= b

0.9553751577527098
3
9


In [35]:
import numpy as np
array_1d = np.array([1, 2, 3])
array_1d

array([1, 2, 3])

In [36]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [38]:
np.zeros((3, 2))


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.reshape(3, 2)

[[1 2 3]
 [4 5 6]]



array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print()

print(a.max())
print(a.mean())
print(a.min())
print(a.std())

[[1 2 3]
 [4 5 6]]

6
3.5
1
1.707825127659933


In [41]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()

print(array_2d.shape)
print(array_2d.dtype)
print(array_2d.size)
print(array_2d.T)

[[1 2 3]
 [4 5 6]]

(2, 3)
int64
6
[[1 4]
 [2 5]
 [3 6]]


In [42]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.array([[1, 2, 3], [1, 2, 3]])
print('a:')
print(a)
print()
print('b:')
print(b)
print()
print('a + b:')
print(a + b)
print()
print('a * b:')
print(a * b)

a:
[[1 2 3]
 [4 5 6]]

b:
[[1 2 3]
 [1 2 3]]

a + b:
[[2 4 6]
 [5 7 9]]

a * b:
[[ 1  4  9]
 [ 4 10 18]]


In [52]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'